[package]
name = "k4arecorder"
version = "0.2.0"
authors = ["Yasuhiro Taniuchi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

azure-kinect = { path = "../azure-kinect" }
azure-kinect-sys = { path = "../azure-kinect-sys" }
clap = "2.33.1"
ctrlc = "3.1.5"
